name: Docker Build-Push-Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: build Docker image
      run: |
        docker build -t test-d-image:latest .

    - name: push Docker image to docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag test-d-image:latest ${{ secrets.DOCKER_USERNAME }}/test-d-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/test-d-image:latest

  run-container:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: run Docker container
      run: docker run -p 80:80 ${{ secrets.DOCKER_USER_NAME }}/test-d-image:latest

  test:
    needs: run-container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        docker pull ghcr.io/liatrio/github-actions/apprentice-action:latest
        docker run -p 80:80 ghcr.io/liatrio/github-actions/apprentice-action:latest
