name: build and run Docker image locally

on:
  push:
    branches:
      - main

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: fetch code
        uses: actions/checkout@v2

      - name: build Docker image
        run: docker build -t test-image .

      - name: run Docker container
        run: docker run -d -p 8080:80 test-image
