on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone code into actions
      uses: actions/checkout@v2
    - name: build Docker image
      run: |
        docker build -t test-d-image:latest .

  run-container:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: run Docker container
      run: docker run -p 80:80 test-d-image:latest

  test:
    needs: run-container
    runs-on: ubuntu-latest
    steps: 
    - name: run tests
      run: |
        docker pull ghcr.io/liatrio/github-actions/apprentice-action:latest
        docker run -p 80:80 ghcr.io/liatrio/github-actions/apprentice-action:latest


