name: build and run Docker image locally and run Liatrio tests

on:
  push:
    branches:
      - main

jobs:
  build-and-run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: fetch code
        uses: actions/checkout@v2

      - name: build Docker image
        run: docker build -t test-image .

      - name: run Docker container
        run: docker run -d -p 80:80 test-image

      - name: run tests
        run: |
           docker pull ghcr.io/liatrio/github-actions/apprentice-action:latest
           docker run -p 8000:8000 ghcr.io/liatrio/github-actions/apprentice-action:latest

        
